# Generated by Django 6.1.1 on 2026-09-30 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
        ('campaigns', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='callrecord',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', 0)), name='call_duration_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='questionresponse',
            constraint=models.UniqueConstraint(fields=('call_record', 'question'), name='unique_response_per_question'),
        ),
    ]
